### PR TITLE
Fixed issue not creating more than 1 project

### LINKED ISSUE #28: [BUG] Creating a new project results in no new project when performing c!create for second time
**Describe the bug**
Initially creating a project works, however creating a second project causes nothing to happen.

**To Reproduce**
1. c!create myproject
2. c!create anotherone
3. c!list results in 1 project "myproject"

**Expected behavior**
A second project is created

**Screenshots**
image

**Additional context**
There is a mistake in the ProjectManager class not incrementing the next key.

### LINKED ISSUE #30: [User Story] As a Developer, I want better unit tests on logical classes to reduce the chance of re-introducing a bug
As previously discussed in #29, improving tests and reducing code repetition is increasingly necessary.

### PR DESCRIPTION
**Pull request by nickmartin1ee7**
Closes #28

### CODE REVIEW

**Comment by srjheam** [comment]
@nickmartin1ee7 Looks good, is there a way to test this though?

**Comment by nickmartin1ee7** [comment]
> @nickmartin1ee7 Looks good, is there a way to test this though?

You're right. There should be a unit test to cover this scenario. Good catch!

**Comment by srjheam** [comment]
I'm thinking if I can do it, but what's the meaning of [FakeProjectManager](https://github.com/Code2Gether-Discord/Code2Gether-Discord-Bot/blob/main/Code2Gether-Discord-Bot.Tests/Fakes/FakeProjectManager.cs) class on Tests? Because just using `new ProjectManager(...)` would do the work and it prevents the devs from changing the same code on multiple areas. If the fake is absolutely necessary, IMHO its entire code should be `Inherit from Projects Manager because it knows what to do`.

Do you agree with me, @nickmartin1ee7?

**Comment by nickmartin1ee7** [comment]
Yeah, that's actually a testable class on its own. Making a fake for that was a mistake since we already pass in a fake repository. Not to mention I broke DRY principle making it.

**Comment by srjheam** [comment]
> Yeah, that's actually a testable class on its own. Making a fake for that was a mistake since we already pass in a fake repository. Not to mention I broke DRY principle making it.

May I open another two issues, one to remove fake classes and one to test the CreateProject method?

**Comment by nickmartin1ee7** [comment]
> > Yeah, that's actually a testable class on its own. Making a fake for that was a mistake since we already pass in a fake repository. Not to mention I broke DRY principle making it.
> 
> May I open another two issues, one to remove fake classes and one to test the CreateProject method?

Yeah. Since the create project is dependant on the other, I'd make it a single refactor user story.

**Comment by nickmartin1ee7** [comment]
@srjheam Can you review this so we can close this PR, and delete this branch?

**Review by srjheam — APPROVED** [review]
Looks good. I only think that it would look better if we don't make a test which depends from the execution of another test and we the instantiation of fake objects should be moved to a specific file apart (I'm doing this on #30).

**Pull request merged**
